# Generated by Django 4.2.6 on 2023-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('apartment', models.CharField(max_length=10, verbose_name='Квартира')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
    ]
