# Generated by Django 4.2.6 on 2023-10-25 16:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
        migrations.AddField(
            model_name='recipient',
            name='send_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата выполнения'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='send_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='время отправки уведомления'),
        ),
    ]
